# Generated by Django 4.2.30 on 2026-10-02 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
            ],
            options={
                'verbose_name_plural': 'directores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('sinopsis', models.TextField(blank=True)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='año')),
                ('duracion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='duración (minutos)')),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('animacion', 'Animación'), ('ciencia_ficcion', 'Ciencia ficción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='género')),
                ('imagen', models.URLField(blank=True, max_length=500, verbose_name='imagen (URL del póster)')),
                ('calificacion_promedio', models.FloatField(default=0, verbose_name='calificación promedio')),
                ('visualizaciones', models.PositiveIntegerField(default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='peliculas.director')),
            ],
            options={
                'verbose_name': 'película',
                'ordering': ['-anio', 'titulo'],
                'unique_together': {('titulo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='HistorialVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('minutos_visto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='minutos vistos')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de visualización',
                'verbose_name_plural': 'historial de visualizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('peliculas', models.ManyToManyField(blank=True, related_name='actores', to='peliculas.pelicula')),
            ],
            options={
                'verbose_name_plural': 'actores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('publica', models.BooleanField(default=False, verbose_name='pública')),
                ('peliculas', models.ManyToManyField(blank=True, related_name='listas', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lista personalizada',
                'verbose_name_plural': 'listas personalizadas',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='puntuación')),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calificación',
                'verbose_name_plural': 'calificaciones',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
    ]
