# Generated by Django 4.2 on 2026-08-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('anio', models.IntegerField(verbose_name='Año de estreno')),
                ('estado', models.CharField(choices=[('VISTA', 'Ya la vi completa'), ('PROGRESO', 'La estoy viendo'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
    ]
