# Generated by Django 4.2 on 2026-08-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Carátula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de estreno'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
